env: "local"
storage_path: "./storage/storage"
ps: "postgresql://postgres:Sanata2628@80.78.243.144:5432/tailly_db"
redisAddr: "80.78.243.144:6379"
http_server:
  address: "localhost:3006"
  timeout: 4s
  idle_timeout: 60s
  